import time

# Angabe der Zahlen
global zahl1, zahl2, zahl3, zahl4, zahl5, zahl6, zahl7, zahl8, zahl9, zahl10
text1 = "Gebe die 1. Zahl ein: "
text2 = "Gebe die 2. Zahl ein: "
text3 = "Gebe die 3. Zahl ein: "
text4 = "Gebe die 4. Zahl ein: "
text5 = "Gebe die 5. Zahl ein: "
text6 = "Gebe die 6. Zahl ein: "
text7 = "Gebe die 7. Zahl ein: "
text8 = "Gebe die 8. Zahl ein: "
text9 = "Gebe die 9. Zahl ein: "
text10 = "Gebe die 10. Zahl ein: "


print('Herzlich Willkommen im Taschenrechner')
print('Programmiert von Oskar Frej.')

time.sleep(1)

print('Wähle zunächst deine Art von Rechnung aus.')
print('')

time.sleep(1)

print('m = Multiplikation')

time.sleep(1)

print('d = Division')

time.sleep(1)

print('a = Addition')

time.sleep(1)

print('s = Subtraktion')

time.sleep(1)

print('g = Gemischt')

time.sleep(1)

rechenart = input('Gebe die Art deiner Rechnung an: ')
if rechenart == "m":
    print('Du hast die Multiplikation ausgewählt')
    time.sleep(1)
    anzahl = input('Gebe an, wieviele Zahlen du multiplizieren möchtest (2-10): ')
    if anzahl == "1":
        print("Wie willst du eine Zahl multiplizieren?")
    elif anzahl == "2":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        time.sleep(1)
        print(zahl1 * zahl2)
    elif anzahl == "3":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        time.sleep(1)
        print(zahl1 * zahl2 * zahl3)
    elif anzahl == "4":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        time.sleep(1)
        print(zahl1 * zahl2 * zahl3 * zahl4)
    elif anzahl == "5":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        time.sleep(1)
        print(zahl1 * zahl2 * zahl3 * zahl4 * zahl5)
    elif anzahl == "6":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        time.sleep(1)
        print(zahl1 * zahl2 * zahl3 * zahl4 * zahl5 * zahl6)
    elif anzahl == "7":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        zahl7 = int(input(text7))
        time.sleep(1)
        print(zahl1 * zahl2 * zahl3 * zahl4 * zahl5 * zahl6 * zahl7)
    elif anzahl == "8":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        zahl7 = int(input(text7))
        zahl8 = int(input(text8))
        time.sleep(1)
        print(zahl1 * zahl2 * zahl3 * zahl4 * zahl5 * zahl6 * zahl7 * zahl8)
    elif anzahl == "9":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        zahl7 = int(input(text7))
        zahl8 = int(input(text8))
        zahl9 = int(input(text9))
        time.sleep(1)
        print(zahl1 * zahl2 * zahl3 * zahl4 * zahl5 * zahl6 * zahl7 * zahl8 * zahl9)
    elif anzahl == "10":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        zahl7 = int(input(text7))
        zahl8 = int(input(text8))
        zahl9 = int(input(text9))
        zahl10 = int(input(text10))
        time.sleep(1)
        print(zahl1 * zahl2 * zahl3 * zahl4 * zahl5 * zahl6 * zahl7 * zahl8 * zahl9 * zahl10)


elif rechenart == "d":
    print('Du hast die Division ausgewählt')
    time.sleep(1)
    anzahl = input('Gebe an, wieviele Zahlen du dividieren möchtest (2-10): ')
    if anzahl == "1":
        print("Wie willst du eine Zahl dividieren?")
    elif anzahl == "2":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        time.sleep(1)
        print(zahl1 / zahl2)
    elif anzahl == "3":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        time.sleep(1)
        print(zahl1 / zahl2 / zahl3)
    elif anzahl == "4":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        time.sleep(1)
        print(zahl1 / zahl2 / zahl3 / zahl4)
    elif anzahl == "5":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        time.sleep(1)
        print(zahl1 / zahl2 / zahl3 / zahl4 / zahl5)
    elif anzahl == "6":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        time.sleep(1)
        print(zahl1 / zahl2 / zahl3 / zahl4 / zahl5 / zahl6)
    elif anzahl == "7":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        zahl7 = int(input(text7))
        time.sleep(1)
        print(zahl1 / zahl2 / zahl3 / zahl4 / zahl5 / zahl6 / zahl7)
    elif anzahl == "8":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        zahl7 = int(input(text7))
        zahl8 = int(input(text8))
        time.sleep(1)
        print(zahl1 / zahl2 / zahl3 / zahl4 / zahl5 / zahl6 / zahl7 / zahl8)
    elif anzahl == "9":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        zahl7 = int(input(text7))
        zahl8 = int(input(text8))
        zahl9 = int(input(text9))
        time.sleep(1)
        print(zahl1 / zahl2 / zahl3 / zahl4 / zahl5 / zahl6 / zahl7 / zahl8 / zahl9)
    elif anzahl == "10":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        zahl7 = int(input(text7))
        zahl8 = int(input(text8))
        zahl9 = int(input(text9))
        zahl10 = int(input(text10))
        time.sleep(1)
        print(zahl1 / zahl2 / zahl3 / zahl4 / zahl5 / zahl6 / zahl7 / zahl8 / zahl9 / zahl10)


elif rechenart == "a":
    print('Du hast die Addition ausgewählt')
    time.sleep(1)

    anzahl = input('Gebe an, wieviele Zahlen du addieren möchtest (2-10): ')
    if anzahl == "1":
        print("Wie willst du eine Zahl addieren?")
    elif anzahl == "2":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        time.sleep(1)
        print(zahl1 + zahl2)
    elif anzahl == "3":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        time.sleep(1)
        print(zahl1 + zahl2 + zahl3)
    elif anzahl == "4":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        time.sleep(1)
        print(zahl1 + zahl2 + zahl3 + zahl4)
    elif anzahl == "5":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        time.sleep(1)
        print(zahl1 + zahl2 + zahl3 + zahl4 + zahl5)
    elif anzahl == "6":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        time.sleep(1)
        print(zahl1 + zahl2 + zahl3 + zahl4 + zahl5 + zahl6)
    elif anzahl == "7":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        zahl7 = int(input(text7))
        time.sleep(1)
        print(zahl1 + zahl2 + zahl3 + zahl4 + zahl5 + zahl6 + zahl7)
    elif anzahl == "8":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        zahl7 = int(input(text7))
        zahl8 = int(input(text8))
        time.sleep(1)
        print(zahl1 + zahl2 + zahl3 + zahl4 + zahl5 + zahl6 + zahl7 + zahl8)
    elif anzahl == "9":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        zahl7 = int(input(text7))
        zahl8 = int(input(text8))
        zahl9 = int(input(text9))
        time.sleep(1)
        print(zahl1 + zahl2 + zahl3 + zahl4 + zahl5 + zahl6 + zahl7 + zahl8 + zahl9)
    elif anzahl == "10":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        zahl7 = int(input(text7))
        zahl8 = int(input(text8))
        zahl9 = int(input(text9))
        zahl10 = int(input(text10))
        time.sleep(1)
        print(zahl1 + zahl2 + zahl3 + zahl4 + zahl5 + zahl6 + zahl7 + zahl8 + zahl9 + zahl10)
elif rechenart == "s":
    print('Du hast die Subtraktion ausgewählt')
    time.sleep(1)

    anzahl = input('Gebe an, wieviele Zahlen du subtrahieren möchtest (2-10): ')
    if anzahl == "1":
        print("Wie willst du eine Zahl addieren?")
    elif anzahl == "2":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        time.sleep(1)
        print(zahl1 - zahl2)
    elif anzahl == "3":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        time.sleep(1)
        print(zahl1 + zahl2 - zahl3)
    elif anzahl == "4":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        time.sleep(1)
        print(zahl1 - zahl2 - zahl3 - zahl4)
    elif anzahl == "5":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        time.sleep(1)
        print(zahl1 - zahl2 - zahl3 - zahl4 - zahl5)
    elif anzahl == "6":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        time.sleep(1)
        print(zahl1 - zahl2 - zahl3 - zahl4 - zahl5 - zahl6)
    elif anzahl == "7":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        zahl7 = int(input(text7))
        time.sleep(1)
        print(zahl1 - zahl2 - zahl3 - zahl4 - zahl5 - zahl6 - zahl7)
    elif anzahl == "8":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        zahl7 = int(input(text7))
        zahl8 = int(input(text8))
        time.sleep(1)
        print(zahl1 - zahl2 - zahl3 - zahl4 - zahl5 - zahl6 - zahl7 - zahl8)
    elif anzahl == "9":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        zahl7 = int(input(text7))
        zahl8 = int(input(text8))
        zahl9 = int(input(text9))
        time.sleep(1)
        print(zahl1 - zahl2 - zahl3 - zahl4 - zahl5 - zahl6 - zahl7 - zahl8 - zahl9)
    elif anzahl == "10":
        zahl1 = int(input(text1))
        zahl2 = int(input(text2))
        zahl3 = int(input(text3))
        zahl4 = int(input(text4))
        zahl5 = int(input(text5))
        zahl6 = int(input(text6))
        zahl7 = int(input(text7))
        zahl8 = int(input(text8))
        zahl9 = int(input(text9))
        zahl10 = int(input(text10))
        time.sleep(1)
        print(zahl1 - zahl2 - zahl3 - zahl4 - zahl5 - zahl6 - zahl7 - zahl8 - zahl9 - zahl10)
elif rechenart == "g":
    print('Du hast die gemischte Rechnung ausgewählt')
    time.sleep(1)
    print('Beim gemischten Rechnen musst du ein bestimmtes Format beachten:')
    time.sleep(1)
    print('Möchtest du eine Zahl multiplizieren, verwendest du "*"')
    time.sleep(2)
    print('Möchtest du eine Zahl dividieren, verwendest du "/"')
    time.sleep(2)
    print('Möchtest du eine Zahl addieren, verwendest du "+"')
    time.sleep(2)
    print('Möchtest du eine Zahl subtrahieren, verwendest du "-"')
    time.sleep(2)
    print('Eine Beispielrechnung würde wie folgt aussehen: ')
    time.sleep(1)
    print('1*5+2')
    time.sleep(1)
    print('Das Ergebnis von dieser Rechnung ergebe dann 7.')
    time.sleep(2)
    print('Du darfst nun deine Rechnung eingeben:')
    time.sleep(1)
    rechnung = input("Gebe deine Rechnung ein: ")
    time.sleep(2)
    ergebnis = eval(rechnung)
    print(ergebnis)

time.sleep(1)
print("Programm erfolgreich beendet.")